using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DBDRandomiser
{
    public static class KillerPerkImages
    {
        public static readonly Dictionary<string, string> KillerMap = new Dictionary<string, string>
        {
            { "A Nurse's Calling",                                          "pack://application:,,,/perk_images/killer_perks/A_Nurse's_Calling.png" },
            { "Agitation",                                                  "pack://application:,,,/perk_images/killer_perks/Agitation.png" },
            { "Alien Instinct",                                             "pack://application:,,,/perk_images/killer_perks/Alien_Instinct.png" },
            { "All-Shaking Thunder",                                        "pack://application:,,,/perk_images/killer_perks/All-Shaking_Thunder.png" },
            { "Awakened Awareness",                                         "pack://application:,,,/perk_images/killer_perks/Awakened_Awareness.png" },
            { "Bamboozle",                                                  "pack://application:,,,/perk_images/killer_perks/Bamboozle.png" },
            { "Barbecue & Chilli",                                          "pack://application:,,,/perk_images/killer_perks/Barbecue_&_Chilli.png" },
            { "Batteries Included",                                         "pack://application:,,,/perk_images/killer_perks/Batteries_Included.png" },
            { "Beast of Prey",                                              "pack://application:,,,/perk_images/killer_perks/Beast_of_Prey.png" },
            { "Bitter Murmur",                                              "pack://application:,,,/perk_images/killer_perks/Bitter_Murmur.png" },
            { "Blood Echo",                                                 "pack://application:,,,/perk_images/killer_perks/Blood_Echo.png" },
            { "Blood Warden",                                               "pack://application:,,,/perk_images/killer_perks/Blood_Warden.png" },
            { "Bloodhound",                                                 "pack://application:,,,/perk_images/killer_perks/Bloodhound.png" },
            { "Brutal Strength",                                            "pack://application:,,,/perk_images/killer_perks/Brutal_Strength.png" },
            { "Call of Brine",                                              "pack://application:,,,/perk_images/killer_perks/Call_of_Brine.png" },
            { "Corrupt Intervention",                                       "pack://application:,,,/perk_images/killer_perks/Corrupt_Intervention.png" },
            { "Coulrophobia",                                               "pack://application:,,,/perk_images/killer_perks/Coulrophobia.png" },
            { "Coup de Grace",                                              "pack://application:,,,/perk_images/killer_perks/Coup_de_Grace.png" },
            { "Cruel Limits",                                               "pack://application:,,,/perk_images/killer_perks/Cruel_Limits.png" },
            { "Dark Arrogance",                                             "pack://application:,,,/perk_images/killer_perks/Dark_Arrogance.png" },
            { "Dark Devotion",                                              "pack://application:,,,/perk_images/killer_perks/Dark_Devotion.png" },
            { "Darkness Revealed",                                          "pack://application:,,,/perk_images/killer_perks/Darkness_Revealed.png" },
            { "Dead Man's Switch",                                          "pack://application:,,,/perk_images/killer_perks/Dead_Man's_Switch.png" },
            { "Deadlock",                                                   "pack://application:,,,/perk_images/killer_perks/Deadlock.png" },
            { "Deathbound",                                                 "pack://application:,,,/perk_images/killer_perks/Deathbound.png" },
            { "Deerstalker",                                                "pack://application:,,,/perk_images/killer_perks/Deerstalker.png" },
            { "Discordance",                                                "pack://application:,,,/perk_images/killer_perks/Discordance.png" },
            { "Dissolution",                                                "pack://application:,,,/perk_images/killer_perks/Dissolution.png" },
            { "Distressing",                                                "pack://application:,,,/perk_images/killer_perks/Distressing.png" },
            { "Dominance",                                                  "pack://application:,,,/perk_images/killer_perks/Dominance.png" },
            { "Dragon's Grip",                                              "pack://application:,,,/perk_images/killer_perks/Dragon's_Grip.png" },
            { "Dying Light",                                                "pack://application:,,,/perk_images/killer_perks/Dying_Light.png" },
            { "Enduring",                                                   "pack://application:,,,/perk_images/killer_perks/Enduring.png" },
            { "Eruption",                                                   "pack://application:,,,/perk_images/killer_perks/Eruption.png" },
            { "Fire Up",                                                    "pack://application:,,,/perk_images/killer_perks/Fire_Up.png" },
            { "Forced Hesitation",                                          "pack://application:,,,/perk_images/killer_perks/Forced_Hesitation.png" },
            { "Forced Penance",                                             "pack://application:,,,/perk_images/killer_perks/Forced_Penance.png" },
            { "Forever Entwined",                                           "pack://application:,,,/perk_images/killer_perks/Forever_Entwined.png" },
            { "Franklin's Demise",                                          "pack://application:,,,/perk_images/killer_perks/Franklins_Demise.png" },
            { "Friends 'til the End",                                       "pack://application:,,,/perk_images/killer_perks/Friends_til_the_End.png" },
            { "Furtive Chase",                                              "pack://application:,,,/perk_images/killer_perks/Furtive_Chase.png" },
            { "Game Afoot",                                                 "pack://application:,,,/perk_images/killer_perks/Game_Afoot.png" },
            { "Gearhead",                                                   "pack://application:,,,/perk_images/killer_perks/Gearhead.png" },
            { "Genetic Limits",                                             "pack://application:,,,/perk_images/killer_perks/Genetic_Limits.png" },
            { "Grim Embrace",                                               "pack://application:,,,/perk_images/killer_perks/Grim_Embrace.png" },
            { "Hex: Blood Favor",                                           "pack://application:,,,/perk_images/killer_perks/Hex_Blood_Favor.png" },
            { "Hex: Crowd Control",                                         "pack://application:,,,/perk_images/killer_perks/Hex_Crowd_Control.png" },
            { "Hex: Devour Hope",                                           "pack://application:,,,/perk_images/killer_perks/Hex_Devour_Hope.png" },
            { "Hex: Face the Darkness",                                     "pack://application:,,,/perk_images/killer_perks/Hex_Face_the_Darkness.png" },
            { "Hex: Haunted Ground",                                        "pack://application:,,,/perk_images/killer_perks/Hex_Haunted_Ground.png" },
            { "Hex: Huntress Lullaby",                                      "pack://application:,,,/perk_images/killer_perks/Hex_Huntress_Lullaby.png" },
            { "Hex: No One Escapes Death",                                  "pack://application:,,,/perk_images/killer_perks/Hex_No_One_Escapes_Death.png" },
            { "Hex: Nothing but Misery",                                    "pack://application:,,,/perk_images/killer_perks/Hex_Nothing_but_Misery.png" },
            { "Hex: Pentimento",                                            "pack://application:,,,/perk_images/killer_perks/Hex_Pentimento.png" },
            { "Hex: Plaything",                                             "pack://application:,,,/perk_images/killer_perks/Hex_Plaything.png" },
            { "Hex: Retribution",                                           "pack://application:,,,/perk_images/killer_perks/Hex_Retribution.png" },
            { "Hex: Ruin",                                                  "pack://application:,,,/perk_images/killer_perks/Hex_Ruin.png" },
            { "Hex: The Third Seal",                                        "pack://application:,,,/perk_images/killer_perks/Hex_The_Third_Seal.png" },
            { "Hex: Thrill of the Hunt",                                    "pack://application:,,,/perk_images/killer_perks/Hex_Thrill_of_the_Hunt.png" },
            { "Hex: Two Can Play",                                          "pack://application:,,,/perk_images/killer_perks/Hex_Two_Can_Play.png" },
            { "Hex: Undying",                                               "pack://application:,,,/perk_images/killer_perks/Hex_Undying.png" },
            { "Hex: Wretched Fate",                                         "pack://application:,,,/perk_images/killer_perks/Hex_Wretched_Fate.png" },
            { "Hoarder",                                                    "pack://application:,,,/perk_images/killer_perks/Hoarder.png" },
            { "Hubris",                                                     "pack://application:,,,/perk_images/killer_perks/Hubris.png" },
            { "Human Greed",                                                "pack://application:,,,/perk_images/killer_perks/Human_Greed.png" },
            { "Hysteria",                                                   "pack://application:,,,/perk_images/killer_perks/Hysteria.png" },
            { "I'm All Ears",                                               "pack://application:,,,/perk_images/killer_perks/I'm_All_Ears.png" },
            { "Infectious Fright",                                          "pack://application:,,,/perk_images/killer_perks/Infectious_Fright.png" },
            { "Insidious",                                                  "pack://application:,,,/perk_images/killer_perks/Insidious.png" },
            { "Iron Grasp",                                                 "pack://application:,,,/perk_images/killer_perks/Iron_Grasp.png" },
            { "Iron Maiden",                                                "pack://application:,,,/perk_images/killer_perks/Iron_Maiden.png" },
            { "Knock Out",                                                  "pack://application:,,,/perk_images/killer_perks/Knock_Out.png" },
            { "Languid Touch",                                              "pack://application:,,,/perk_images/killer_perks/Languid_Touch.png" },
            { "Lethal Pursuer",                                             "pack://application:,,,/perk_images/killer_perks/Lethal_Pursuer.png" },
            { "Leverage",                                                   "pack://application:,,,/perk_images/killer_perks/Leverage.png" },
            { "Lightborn",                                                  "pack://application:,,,/perk_images/killer_perks/Lightborn.png" },
            { "Machine Learning",                                           "pack://application:,,,/perk_images/killer_perks/Machine_Learning.png" },
            { "Mad Grit",                                                   "pack://application:,,,/perk_images/killer_perks/Mad_Grit.png" },
            { "Make Your Choice",                                           "pack://application:,,,/perk_images/killer_perks/Make_Your_Choice.png" },
            { "Merciless Storm",                                            "pack://application:,,,/perk_images/killer_perks/Merciless_Storm.png" },
            { "Mindbreaker",                                                "pack://application:,,,/perk_images/killer_perks/Mindbreaker.png" },
            { "Monitor & Abuse",                                            "pack://application:,,,/perk_images/killer_perks/Monitor_&_Abuse.png" },
            { "Nemesis",                                                    "pack://application:,,,/perk_images/killer_perks/Nemesis.png" },
            { "No Quarter",                                                 "pack://application:,,,/perk_images/killer_perks/No_Quarter.png" },
            { "No Way Out",                                                 "pack://application:,,,/perk_images/killer_perks/No_Way_Out.png" },
            { "None are Free",                                              "pack://application:,,,/perk_images/killer_perks/None_are_Free.png" },
            { "Nowhere to Hide",                                            "pack://application:,,,/perk_images/killer_perks/Nowhere_to_Hide.png" },
            { "Oppression",                                                 "pack://application:,,,/perk_images/killer_perks/Oppression.png" },
            { "Overcharge",                                                 "pack://application:,,,/perk_images/killer_perks/Overcharge.png" },
            { "Overwhelming Presence",                                      "pack://application:,,,/perk_images/killer_perks/Overwhelming_Presence.png" },
            { "Play with Your Food",                                        "pack://application:,,,/perk_images/killer_perks/Play_with_Your_Food.png" },
            { "Pop Goes the Weasel",                                        "pack://application:,,,/perk_images/killer_perks/Pop_Goes_the_Weasel.png" },
            { "Predator",                                                   "pack://application:,,,/perk_images/killer_perks/Predator.png" },
            { "Rancor",                                                     "pack://application:,,,/perk_images/killer_perks/Rancor.png" },
            { "Rapid Brutality",                                            "pack://application:,,,/perk_images/killer_perks/Rapid_Brutality.png" },
            { "Remember Me",                                                "pack://application:,,,/perk_images/killer_perks/Remember_Me.png" },
            { "Save the Best for Last",                                     "pack://application:,,,/perk_images/killer_perks/Save_the_Best_for_Last.png" },
            { "Scourge Hook: Floods of Rage",                               "pack://application:,,,/perk_images/killer_perks/Scourge_Hook_Floods_of_Rage.png" },
            { "Scourge Hook: Gift of Pain",                                 "pack://application:,,,/perk_images/killer_perks/Scourge_Hook_Gift_of_Pain.png" },
            { "Scourge Hook: Hangman's Trick",                              "pack://application:,,,/perk_images/killer_perks/Scourge_Hook_Hangman's_Trick.png" },
            { "Scourge Hook: Jagged Compass",                               "pack://application:,,,/perk_images/killer_perks/Scourge_Hook_Jagged_Compass.png" },
            { "Scourge Hook: Monstrous Shrine",                             "pack://application:,,,/perk_images/killer_perks/Scourge_Hook_Monstrous_Shrine.png" },
            { "Scourge Hook: Pain Resonance",                               "pack://application:,,,/perk_images/killer_perks/Scourge_Hook_Pain_Resonance.png" },
            { "Septic Touch",                                               "pack://application:,,,/perk_images/killer_perks/Septic_Touch.png" },
            { "Shadowborn",                                                 "pack://application:,,,/perk_images/killer_perks/Shadowborn.png" },
            { "Shattered Hope",                                             "pack://application:,,,/perk_images/killer_perks/Shattered_Hope.png" },
            { "Sloppy Butcher",                                             "pack://application:,,,/perk_images/killer_perks/Sloppy_Butcher.png" },
            { "Spies from the Shadows",                                     "pack://application:,,,/perk_images/killer_perks/Spies_from_the_Shadows.png" },
            { "Spirit Fury",                                                "pack://application:,,,/perk_images/killer_perks/Spirit_Fury.png" },
            { "Starstruck",                                                 "pack://application:,,,/perk_images/killer_perks/Starstruck.png" },
            { "Stridor",                                                    "pack://application:,,,/perk_images/killer_perks/Stridor.png" },
            { "Superior Anatomy",                                           "pack://application:,,,/perk_images/killer_perks/Superior_Anatomy.png" },
            { "Surge",                                                      "pack://application:,,,/perk_images/killer_perks/Surge.png" },
            { "Surveillance",                                               "pack://application:,,,/perk_images/killer_perks/Surveillance.png" },
            { "Terminus",                                                   "pack://application:,,,/perk_images/killer_perks/Terminus.png" },
            { "Territorial Imperative",                                     "pack://application:,,,/perk_images/killer_perks/Territorial_Imperative.png" },
            { "Thanatophobia",                                              "pack://application:,,,/perk_images/killer_perks/Thanatophobia.png" },
            { "Thrilling Tremors",                                          "pack://application:,,,/perk_images/killer_perks/Thrilling_Tremors.png" },
            { "THWACK!",                                                    "pack://application:,,,/perk_images/killer_perks/THWACK!.png" },
            { "Tinkerer",                                                   "pack://application:,,,/perk_images/killer_perks/Tinkerer.png" },
            { "Trail of Torment",                                           "pack://application:,,,/perk_images/killer_perks/Trail_of_Torment.png" },
            { "Ultimate Weapon",                                            "pack://application:,,,/perk_images/killer_perks/Ultimate_Weapon.png" },
            { "Unbound",                                                    "pack://application:,,,/perk_images/killer_perks/Unbound.png" },
            { "Undone",                                                     "pack://application:,,,/perk_images/killer_perks/Undone.png" },
            { "Unforeseen",                                                 "pack://application:,,,/perk_images/killer_perks/Unforeseen.png" },
            { "Unnerving Presence",                                         "pack://application:,,,/perk_images/killer_perks/Unnerving_Presence.png" },
            { "Unrelenting",                                                "pack://application:,,,/perk_images/killer_perks/Unrelenting.png" },
            { "Weave Attunement",                                           "pack://application:,,,/perk_images/killer_perks/Weave_Attunement.png" },
            { "Whispers",                                                   "pack://application:,,,/perk_images/killer_perks/Whispers.png" },
            { "Zanshin Tactics",                                            "pack://application:,,,/perk_images/killer_perks/Zanshin_Tactics.png" }
        };
    }

    public static class SurvivorPerkImages
    {
        public static readonly Dictionary<string, string> SurvivorMap = new Dictionary<string, string>
        {
            {"Ace in the Hole",                                             "pack://application:,,,/perk_images/survivor_perks/Ace_in_the_Hole.png"},
            {"Adrenaline",                                                  "pack://application:,,,/perk_images/survivor_perks/Adrenaline.png"},
            {"Aftercare",                                                   "pack://application:,,,/perk_images/survivor_perks/Aftercare.png"},
            {"Alert",                                                       "pack://application:,,,/perk_images/survivor_perks/Alert.png"},
            {"Any Means Necessary",                                         "pack://application:,,,/perk_images/survivor_perks/Any_Means_Necessary.png"},
            {"Appraisal",                                                   "pack://application:,,,/perk_images/survivor_perks/Appraisal.png"},
            {"Autodidact",                                                  "pack://application:,,,/perk_images/survivor_perks/Autodidact.png"},
            {"Babysitter",                                                  "pack://application:,,,/perk_images/survivor_perks/Babysitter.png"},
            {"Background Player",                                           "pack://application:,,,/perk_images/survivor_perks/Background_Player.png"},
            {"Balanced Landing",                                            "pack://application:,,,/perk_images/survivor_perks/Balanced_Landing.png"},
            {"Bardic Inspiration",                                          "pack://application:,,,/perk_images/survivor_perks/Bardic_Inspiration.png"},
            {"Better than New",                                             "pack://application:,,,/perk_images/survivor_perks/Better_than_New.png"},
            {"Better Together",                                             "pack://application:,,,/perk_images/survivor_perks/Better_Together.png"},
            {"Bite the Bullet",                                             "pack://application:,,,/perk_images/survivor_perks/Bite_the_Bullet.png"},
            {"Blast Mine",                                                  "pack://application:,,,/perk_images/survivor_perks/Blast_Mine.png"},
            {"Blood Pact",                                                  "pack://application:,,,/perk_images/survivor_perks/Blood_Pact.png"},
            {"Blood Rush",                                                  "pack://application:,,,/perk_images/survivor_perks/Blood_Rush.png"},
            {"Boil Over",                                                   "pack://application:,,,/perk_images/survivor_perks/Boil_Over.png"},
            {"Bond",                                                        "pack://application:,,,/perk_images/survivor_perks/Bond.png"},
            {"Boon: Circle of Healing",                                     "pack://application:,,,/perk_images/survivor_perks/Boon_Circle_of_Healing.png"},
            {"Boon: Dark Theory",                                           "pack://application:,,,/perk_images/survivor_perks/Boon_Dark_Theory.png"},
            {"Boon: Exponential",                                           "pack://application:,,,/perk_images/survivor_perks/Boon_Exponential.png"},
            {"Boon: Illumination",                                          "pack://application:,,,/perk_images/survivor_perks/Boon_Illumination.png"},
            {"Boon: Shadow Step",                                           "pack://application:,,,/perk_images/survivor_perks/Boon_Shadow_Step.png"},
            {"Borrowed Time",                                               "pack://application:,,,/perk_images/survivor_perks/Borrowed_Time.png"},
            {"Botany Knowledge",                                            "pack://application:,,,/perk_images/survivor_perks/Botany_Knowledge.png"},
            {"Breakdown",                                                   "pack://application:,,,/perk_images/survivor_perks/Breakdown.png"},
            {"Breakout",                                                    "pack://application:,,,/perk_images/survivor_perks/Breakout.png"},
            {"Buckle Up",                                                   "pack://application:,,,/perk_images/survivor_perks/Buckle_Up.png"},
            {"Built to Last",                                               "pack://application:,,,/perk_images/survivor_perks/Built_to_Last.png"},
            {"Calm Spirit",                                                 "pack://application:,,,/perk_images/survivor_perks/Calm_Spirit.png"},
            {"Camaraderie",                                                 "pack://application:,,,/perk_images/survivor_perks/Camaraderie.png"},
            {"Champion of Light",                                           "pack://application:,,,/perk_images/survivor_perks/Champion_of_Light.png"},
            {"Chemical Trap",                                               "pack://application:,,,/perk_images/survivor_perks/Chemical_Trap.png"},
            {"Clairvoyance",                                                "pack://application:,,,/perk_images/survivor_perks/Clairvoyance.png"},
            {"Clean Break",                                                 "pack://application:,,,/perk_images/survivor_perks/Clean_Break.png"},
            {"Corrective Action",                                           "pack://application:,,,/perk_images/survivor_perks/Corrective_Action.png"},
            {"Counterforce",                                                "pack://application:,,,/perk_images/survivor_perks/Counterforce.png"},
            {"Cut Loose",                                                   "pack://application:,,,/perk_images/survivor_perks/Cut_Loose.png"},
            {"Déjà Vu",                                                     "pack://application:,,,/perk_images/survivor_perks/Deja_Vu.png"},
            {"Dance With Me",                                               "pack://application:,,,/perk_images/survivor_perks/Dance_With_Me.png"},
            {"Dark Sense",                                                  "pack://application:,,,/perk_images/survivor_perks/Dark_Sense.png"},
            {"Dead Hard",                                                   "pack://application:,,,/perk_images/survivor_perks/Dead_Hard.png"},
            {"Deadline",                                                    "pack://application:,,,/perk_images/survivor_perks/Deadline.png"},
            {"Deception",                                                   "pack://application:,,,/perk_images/survivor_perks/Deception.png"},
            {"Decisive Strike",                                             "pack://application:,,,/perk_images/survivor_perks/Decisive_Strike.png"},
            {"Deliverance",                                                 "pack://application:,,,/perk_images/survivor_perks/Deliverance.png"},
            {"Desperate Measures",                                          "pack://application:,,,/perk_images/survivor_perks/Desperate_Measures.png"},
            {"Detective's Hunch",                                           "pack://application:,,,/perk_images/survivor_perks/Detective's_Hunch.png"},
            {"Distortion",                                                  "pack://application:,,,/perk_images/survivor_perks/Distortion.png"},
            {"Diversion",                                                   "pack://application:,,,/perk_images/survivor_perks/Diversion.png"},
            {"Do No Harm",                                                  "pack://application:,,,/perk_images/survivor_perks/Do_No_Harm.png"},
            {"Dramaturgy",                                                  "pack://application:,,,/perk_images/survivor_perks/Dramaturgy.png"},
            {"Duty of Care",                                                "pack://application:,,,/perk_images/survivor_perks/Duty_of_Care.png"},
            {"Empathic Connection",                                         "pack://application:,,,/perk_images/survivor_perks/Empathic_Connection.png"},
            {"Empathy",                                                     "pack://application:,,,/perk_images/survivor_perks/Empathy.png"},
            {"Exultation",                                                  "pack://application:,,,/perk_images/survivor_perks/Exultation.png"},
            {"Eyes of Belmont",                                             "pack://application:,,,/perk_images/survivor_perks/Eyes_of_Belmont.png"},
            {"Fast Track",                                                  "pack://application:,,,/perk_images/survivor_perks/Fast_Track.png"},
            {"Finesse",                                                     "pack://application:,,,/perk_images/survivor_perks/Finesse.png"},
            {"Fixated",                                                     "pack://application:,,,/perk_images/survivor_perks/Fixated.png"},
            {"Flashbang",                                                   "pack://application:,,,/perk_images/survivor_perks/Flashbang.png"},
            {"Flip-Flop",                                                   "pack://application:,,,/perk_images/survivor_perks/Flip-Flop.png"},
            {"Fogwise",                                                     "pack://application:,,,/perk_images/survivor_perks/Fogwise.png"},
            {"For the People",                                              "pack://application:,,,/perk_images/survivor_perks/For_the_People.png"},
            {"Friendly Competition",                                        "pack://application:,,,/perk_images/survivor_perks/Friendly_Competition.png"},
            {"Hardened",                                                    "pack://application:,,,/perk_images/survivor_perks/Hardened.png"},
            {"Head On",                                                     "pack://application:,,,/perk_images/survivor_perks/Head_On.png"},
            {"Hope",                                                        "pack://application:,,,/perk_images/survivor_perks/Hope.png"},
            {"Hyperfocus",                                                  "pack://application:,,,/perk_images/survivor_perks/Hyperfocus.png"},
            {"Inner Focus",                                                 "pack://application:,,,/perk_images/survivor_perks/Inner_Focus.png"},
            {"Inner Strength",                                              "pack://application:,,,/perk_images/survivor_perks/Inner_Strength.png"},
            {"Invocation: Treacherous Crows",                               "pack://application:,,,/perk_images/survivor_perks/Invocation_Treacherous_Crows.png"},
            {"Invocation: Weaving Spiders",                                 "pack://application:,,,/perk_images/survivor_perks/Invocation_Weaving_Spiders.png"},
            {"Iron Will",                                                   "pack://application:,,,/perk_images/survivor_perks/Iron_Will.png"},
            {"Kindred",                                                     "pack://application:,,,/perk_images/survivor_perks/Kindred.png"},
            {"Leader",                                                      "pack://application:,,,/perk_images/survivor_perks/Leader.png"},
            {"Left Behind",                                                 "pack://application:,,,/perk_images/survivor_perks/Left_Behind.png"},
            {"Light-Footed",                                                "pack://application:,,,/perk_images/survivor_perks/Light-Footed.png"},
            {"Lightweight",                                                 "pack://application:,,,/perk_images/survivor_perks/Lightweight.png"},
            {"Lithe",                                                       "pack://application:,,,/perk_images/survivor_perks/Lithe.png"},
            {"Low Profile",                                                 "pack://application:,,,/perk_images/survivor_perks/Low_Profile.png"},
            {"Lucky Break",                                                 "pack://application:,,,/perk_images/survivor_perks/Lucky_Break.png"},
            {"Lucky Star",                                                  "pack://application:,,,/perk_images/survivor_perks/Lucky_Star.png"},
            {"Made for This",                                               "pack://application:,,,/perk_images/survivor_perks/Made_for_This.png"},
            {"Mettle of Man",                                               "pack://application:,,,/perk_images/survivor_perks/Mettle_of_Man.png"},
            {"Mirrored Illusion",                                           "pack://application:,,,/perk_images/survivor_perks/Mirrored_Illusion.png"},
            {"Moment of Glory",                                             "pack://application:,,,/perk_images/survivor_perks/Moment_of_Glory.png"},
            {"No Mither",                                                   "pack://application:,,,/perk_images/survivor_perks/No_Mither.png"},
            {"No One Left Behind",                                          "pack://application:,,,/perk_images/survivor_perks/No_One_Left_Behind.png"},
            {"Object of Obsession",                                         "pack://application:,,,/perk_images/survivor_perks/Object_of_Obsession.png"},
            {"Off the Record",                                              "pack://application:,,,/perk_images/survivor_perks/Off_the_Record.png"},
            {"Open-Handed",                                                 "pack://application:,,,/perk_images/survivor_perks/Open-Handed.png"},
            {"Overcome",                                                    "pack://application:,,,/perk_images/survivor_perks/Overcome.png"},
            {"Overzealous",                                                 "pack://application:,,,/perk_images/survivor_perks/Overzealous.png"},
            {"Parental Guidance",                                           "pack://application:,,,/perk_images/survivor_perks/Parental_Guidance.png"},
            {"Pharmacy",                                                    "pack://application:,,,/perk_images/survivor_perks/Pharmacy.png"},
            {"Plot Twist",                                                  "pack://application:,,,/perk_images/survivor_perks/Plot_Twist.png"},
            {"Plunderer's Instinct",                                        "pack://application:,,,/perk_images/survivor_perks/Plunderer's_Instinct.png"},
            {"Poised",                                                      "pack://application:,,,/perk_images/survivor_perks/Poised.png"},
            {"Potential Energy",                                            "pack://application:,,,/perk_images/survivor_perks/Potential_Energy.png"},
            {"Power Struggle",                                              "pack://application:,,,/perk_images/survivor_perks/Power_Struggle.png"},
            {"Premonition",                                                 "pack://application:,,,/perk_images/survivor_perks/Premonition.png"},
            {"Prove Thyself",                                               "pack://application:,,,/perk_images/survivor_perks/Prove_Thyself.png"},
            {"Quick & Quiet",                                               "pack://application:,,,/perk_images/survivor_perks/Quick_&_Quiet.png"},
            {"Quick Gambit",                                                "pack://application:,,,/perk_images/survivor_perks/Quick_Gambit.png"},
            {"Rapid Response",                                              "pack://application:,,,/perk_images/survivor_perks/Rapid_Response.png"},
            {"Reactive Healing",                                            "pack://application:,,,/perk_images/survivor_perks/Reactive_Healing.png"},
            {"Reassurance",                                                 "pack://application:,,,/perk_images/survivor_perks/Reassurance.png"},
            {"Red Herring",                                                 "pack://application:,,,/perk_images/survivor_perks/Red_Herring.png"},
            {"Repressed Alliance",                                          "pack://application:,,,/perk_images/survivor_perks/Repressed_Alliance.png"},
            {"Residual Manifest",                                           "pack://application:,,,/perk_images/survivor_perks/Residual_Manifest.png"},
            {"Resilience",                                                  "pack://application:,,,/perk_images/survivor_perks/Resilience.png"},
            {"Resurgence",                                                  "pack://application:,,,/perk_images/survivor_perks/Resurgence.png"},
            {"Rookie Spirit",                                               "pack://application:,,,/perk_images/survivor_perks/Rookie_Spirit.png"},
            {"Saboteur",                                                    "pack://application:,,,/perk_images/survivor_perks/Saboteur.png"},
            {"Scavenger",                                                   "pack://application:,,,/perk_images/survivor_perks/Scavenger.png"},
            {"Scene Partner",                                               "pack://application:,,,/perk_images/survivor_perks/Scene_Partner.png"},
            {"Second Wind",                                                 "pack://application:,,,/perk_images/survivor_perks/Second_Wind.png"},
            {"Self-Care",                                                   "pack://application:,,,/perk_images/survivor_perks/Self-Care.png"},
            {"Self-Preservation",                                           "pack://application:,,,/perk_images/survivor_perks/Self-Preservation.png"},
            {"Shoulder the Burden",                                         "pack://application:,,,/perk_images/survivor_perks/Shoulder_the_Burden.png"},
            {"Slippery Meat",                                               "pack://application:,,,/perk_images/survivor_perks/Slippery_Meat.png"},
            {"Small Game",                                                  "pack://application:,,,/perk_images/survivor_perks/Small_Game.png"},
            {"Smash Hit",                                                   "pack://application:,,,/perk_images/survivor_perks/Smash_Hit.png"},
            {"Sole Survivor",                                               "pack://application:,,,/perk_images/survivor_perks/Sole_Survivor.png"},
            {"Solidarity",                                                  "pack://application:,,,/perk_images/survivor_perks/Solidarity.png"},
            {"Soul Guard",                                                  "pack://application:,,,/perk_images/survivor_perks/Soul_Guard.png"},
            {"Specialist",                                                  "pack://application:,,,/perk_images/survivor_perks/Specialist.png"},
            {"Spine Chill",                                                 "pack://application:,,,/perk_images/survivor_perks/Spine_Chill.png"},
            {"Sprint Burst",                                                "pack://application:,,,/perk_images/survivor_perks/Sprint_Burst.png"},
            {"Stake Out",                                                   "pack://application:,,,/perk_images/survivor_perks/Stake_Out.png"},
            {"Still Sight",                                                 "pack://application:,,,/perk_images/survivor_perks/Still_Sight.png"},
            {"Streetwise",                                                  "pack://application:,,,/perk_images/survivor_perks/Streetwise.png"},
            {"Strength in Shadows",                                         "pack://application:,,,/perk_images/survivor_perks/Strength_in_Shadows.png"},
            {"Teamwork: Collective Stealth",                                "pack://application:,,,/perk_images/survivor_perks/Teamwork_Collective_Stealth.png"},
            {"Teamwork: Power of Two",                                      "pack://application:,,,/perk_images/survivor_perks/Teamwork_Power_of_Two.png"},
            {"Technician",                                                  "pack://application:,,,/perk_images/survivor_perks/Technician.png"},
            {"Tenacity",                                                    "pack://application:,,,/perk_images/survivor_perks/Tenacity.png"},
            {"This Is Not Happening",                                       "pack://application:,,,/perk_images/survivor_perks/This_Is_Not_Happening.png"},
            {"Troubleshooter",                                              "pack://application:,,,/perk_images/survivor_perks/Troubleshooter.png"},
            {"Unbreakable",                                                 "pack://application:,,,/perk_images/survivor_perks/Unbreakable.png"},
            {"Up the Ante",                                                 "pack://application:,,,/perk_images/survivor_perks/Up_the_Ante.png"},
            {"Urban Evasion",                                               "pack://application:,,,/perk_images/survivor_perks/Urban_Evasion.png"},
            {"Vigil",                                                       "pack://application:,,,/perk_images/survivor_perks/Vigil.png"},
            {"Visionary",                                                   "pack://application:,,,/perk_images/survivor_perks/Visionary.png"},
            {"Wake Up!",                                                    "pack://application:,,,/perk_images/survivor_perks/Wake_Up!.png"},
            {"We'll Make It",                                               "pack://application:,,,/perk_images/survivor_perks/We'll_Make_It.png"},
            {"We're Gonna Live Forever",                                    "pack://application:,,,/perk_images/survivor_perks/We're_Gonna_Live_Forever.png"},
            {"Wicked",                                                      "pack://application:,,,/perk_images/survivor_perks/Wicked.png"},
            {"Windows of Opportunity",                                      "pack://application:,,,/perk_images/survivor_perks/Windows_of_Opportunity.png"},
            {"Wiretap",                                                     "pack://application:,,,/perk_images/survivor_perks/Wiretap.png"}
        };
    }
}